f=open('lib/screens/admin/admin_screen.dart',encoding='utf-8') 
c=f.read() 
f.close() 
c=c.replace('`\n``\n``\n','') 
c=c.replace("    import 'dart:convert';",'') 
c=c.replace("    import 'package:http/http.dart' as http;",'') 
c=c.replace("    import '../../services/api_service.dart';",'') 
f=open('lib/screens/admin/admin_screen.dart','w',encoding='utf-8') 
f.write(c) 
f.close() 
